name: roadcop
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.2.1
  flame_splash_screen: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: Alarm
      fonts:
       - asset: assets/fonts/alarm_clock.ttf
    - family: Arcade
      fonts:
       - asset: assets/fonts/arcade.ttf
    - family: Pointless
      fonts:
       - asset: assets/fonts/pointless.ttf
    - family: Nero
      fonts:
       - asset: assets/fonts/nero.otf
